apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgw
  template:
    metadata:
      labels:
        app: pgw
    spec:
      containers:
      - image: pgw
        imagePullPolicy: Never
        name: pgw
        resources: 
          limits:
            cpu: 1
            memory: "1024Mi"
          requests: 
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080