apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName}}
spec:
  {{- with .Values.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector: 
    app: {{ .Values.name }}
  type: {{ .Values.nodeType}}
